name = "noyd3v/rugplay_shill"
version = "0.1.0"
description = 'This is a neat little way to plug your rugplay coin'
license = "MIT"

[target]
environment = "lune"
bin = "src/main.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[engines]
lune = "^0.8.9"
